name: Deploy to EKS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli:2.3.1
      volumes:
        - name: shared-data
          emptyDir: {}
      command: ["sleep", "infinity"]
    steps:
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: AKIAQ5ZFAJFAJ66PXGU2
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: us-west-2
        run: |
          aws eks update-kubeconfig --name eks-cluster-test
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
      - name: Deploy NGINX resources
        run: |
          kubectl apply -f nginx-pod.yml
          kubectl apply -f nginx-service.yml
          kubectl apply -f nginx-replicaset.yml
          kubectl apply -f nginx-deployment.yml
