name: deploy to EKS
on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.25.0" # default is latest stable
        id: install

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     aws-secret-access-key: ${{secrets.AWS_SECRET_KEY_ID}}
      #     aws-region: ${{secrets.AWS_REGION}}

      - name: Deploy to EKS
        run: |
          aws configure set aws_access_key_id AKIASZFRB32E3IQVXH56
          aws configure set aws_secret_access_key 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
          aws configure set default.region us-east-1

          aws ec2 describe-instances


          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          aws eks update-kubeconfig --name sprints-eks --region us-east-1
          kubectl config current-context
          kubectl apply -f nginx-pod.yml --kubeconfig /home/runner/.kube/config
          kubectl apply -f nginx-service.yml --kubeconfig /home/runner/.kube/config
          kubectl apply -f nginx-replicaset.yml --kubeconfig /home/runner/.kube/config
          kubectl apply -f nginx-deployment.yml --kubeconfig /home/runner/.kube/config
